import { getBTCAddressFromMnemonic } from '../src/chains/btc';
import { getEthAddressFromMnemonic } from '../src/chains/eth';

// generated by https://iancoleman.io/bip39/
const mnemonic =
  'boil rich approve sustain joke repeat wait loud split runway mix pepper shield click tackle';

test('BTC Address', async () => {
  const { address } = getBTCAddressFromMnemonic(mnemonic);

  expect(address).toBe('1o7bH86mLUfcf5nNiMerZzfJnU47aYUQK');
});

test('ETH Address', async () => {
  const { address } = getEthAddressFromMnemonic(mnemonic);

  expect(address).toBe('0xdbc47CC91b309eb5429bD376B98fDEc815f65986');
});
